# Generated by Django 5.2 on 2025-06-23 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0010_feedbackseccion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedbackseccion",
            name="fecha_feedback",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
