# Generated by Django 5.2 on 2025-06-23 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0011_alter_feedbackseccion_fecha_feedback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recurso",
            name="url_recurso",
            field=models.URLField(max_length=1000, null=True),
        ),
    ]
