# Generated by Django 5.2 on 2025-06-24 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0012_alter_recurso_url_recurso"),
        ("users", "0003_usuario_tipo_de_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comentario",
            fields=[
                ("id_comentario", models.AutoField(primary_key=True, serialize=False)),
                ("contenido_comentario", models.TextField()),
                (
                    "puntuacion_curso",
                    models.IntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        help_text="Puntuación del curso (1 a 5 estrellas).",
                    ),
                ),
                ("fecha_creacion_comentario", models.DateTimeField(auto_now_add=True)),
                (
                    "autor_comentario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.estudiante",
                    ),
                ),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="education.curso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comentario de Curso",
                "verbose_name_plural": "Comentarios de Curso",
            },
        ),
    ]
