# Generated by Django 5.2 on 2025-06-25 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0013_comentario"),
        ("users", "0003_usuario_tipo_de_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comentario",
            name="curso",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comentarios_curso",
                to="education.curso",
            ),
        ),
        migrations.CreateModel(
            name="InscripcionCurso",
            fields=[
                ("id_inscripcion", models.AutoField(primary_key=True, serialize=False)),
                ("fecha_inscripcion", models.DateField(auto_now_add=True)),
                ("completado", models.BooleanField(default=False)),
                (
                    "curso_inscripcion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="education.curso",
                    ),
                ),
                (
                    "estudiante_inscripcion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.estudiante",
                    ),
                ),
            ],
        ),
    ]
