# Generated by Django 5.2 on 2025-06-25 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0014_alter_comentario_curso_inscripcioncurso"),
        ("users", "0003_usuario_tipo_de_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="EstudianteInstitucion",
            fields=[
                (
                    "id_estudiante_institucion",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "estudiante_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.estudiante",
                    ),
                ),
                (
                    "institucion_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="education.institucion",
                    ),
                ),
            ],
            options={
                "unique_together": {("institucion_id", "estudiante_id")},
            },
        ),
    ]
