# Generated by Django 5.2 on 2025-06-26 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0015_estudianteinstitucion"),
        ("users", "0003_usuario_tipo_de_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="inscripcioncurso",
            name="porcentaje_progreso",
            field=models.FloatField(
                default=0.0,
                help_text="Porcentaje de secciones completadas en este curso.",
            ),
        ),
        migrations.CreateModel(
            name="ProgresoSeccion",
            fields=[
                (
                    "id_progreso_seccion",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "fecha_completado",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Fecha y hora en que la sección fue completada.",
                    ),
                ),
                (
                    "estudiante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progreso_secciones",
                        to="users.estudiante",
                    ),
                ),
                (
                    "seccion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progreso_estudiantes",
                        to="education.seccion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Progreso de Sección",
                "verbose_name_plural": "Progreso de Secciones",
                "unique_together": {("estudiante", "seccion")},
            },
        ),
    ]
