# Generated by Django 5.2 on 2025-06-30 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0017_progresoseccion_from_inscripcion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="progresoseccion",
            name="from_inscripcion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="progreso_de_inscripcion",
                to="education.inscripcioncurso",
            ),
        ),
    ]
