# Generated by Django 5.2 on 2025-06-30 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0018_alter_progresoseccion_from_inscripcion"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certificado",
            fields=[
                ("id_certificado", models.AutoField(primary_key=True, serialize=False)),
                ("fecha_emision_certificado", models.DateTimeField(auto_now_add=True)),
                ("url_certificado", models.URLField()),
                (
                    "certificado_de_inscripcion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificado_inscripcion",
                        to="education.inscripcioncurso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Certificado",
                "verbose_name_plural": "Certificados",
                "ordering": ["-fecha_emision_certificado"],
            },
        ),
    ]
