# Generated by Django 5.2 on 2025-06-19 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoUsuario",
            fields=[
                (
                    "id_tipo_usuario",
                    models.AutoField(
                        help_text="ID tipo user", primary_key=True, serialize=False
                    ),
                ),
                ("tipo_usuario", models.CharField(max_length=15)),
            ],
            options={
                "verbose_name": "Tipo de Usuario",
                "verbose_name_plural": "Tipos de Usuarios",
            },
        ),
    ]
