# Generated by Django 5.2 on 2025-06-19 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_tipousuario"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="tipo_de_user",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.PROTECT,
                to="users.tipousuario",
            ),
        ),
    ]
