name: Frontend CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Instalar dependencias
        run: |
          cd Frontend
          npm install

      - name: Compilar proyecto Vite
        run: |
          cd Frontend
          npm run build
      - name: Ejecutar linter (ESLint)
        run: |
          cd Frontend
          npm run lint
      - name: Format check (Prettier)
        run: |
          cd Frontend
          npx prettier --check .
      - name: Start preview server
        run: |
          cd Frontend
          npm run preview
      
