name: Django CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Instalar dependencias del backend
        run: |
          cd Back
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar pruebas Django
        run: |
          cd Back
          python manage.py test
