name: Django Models CI

on:
  push:
    branches:
      - feat/models
    paths:
      - 'Backend/Backend/apps/education/models.py'
  pull_request:
    branches:
      - feat/models
    paths:
      - 'Backend/Backend/apps/education/models.py'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          cd Backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar pruebas
        run: |
          cd Backend
          python manage.py test
